import Layout from '@/components/layout/Layout'
import Head from 'next/head'
import favicon from '@/public/images/favicon.png';
import ContactsPage from '@/components/templates/ContactsPage/ContactsPage';


export default function Catalog(){

    return (
        <>
          <Head>
            <title>Others - Корзина</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href={favicon.src} />
          </Head>
          <Layout>
            <ContactsPage/>
          </Layout>
        </>
      )
}