import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from '@/components/elements/Button'
import { AuthPage } from '@/components/templates/AuthPage/AuthPage'
import { Modal } from '@/components/layout/Modal'
import { Cross } from '@/components/elements/Cross'

export default function Auth() {
  return (
    <>
      <Head>
        <title>Others</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./public/images/favicon.png" />
      </Head>
      <Modal childred={<AuthPage/>} />

      <Cross size={60}/>
    </>
  )
}
