import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from '@/components/elements/Button/Button'
import { AuthPage } from '@/components/templates/AuthPage/AuthPage'
import { Modal } from '@/components/layout/Modal'
import { Cross } from '@/components/elements/Cross/Cross'
import { Header } from '@/components/modules/Header/Header'
import { Dropdown } from '@/components/modules/Header/Dropdown'
import favicon from '@/public/images/favicon.png';
import { Footer } from '@/components/modules/Footer/Footer'
import Layout from '@/components/layout/Layout'
import { HomePage } from '@/components/templates/HomePage/HomePage'
import { useRedirectByUserCheck } from '@/hooks/useRedirectByUserCheck'
//import globalStyles from '../styles/globals.scss';

export default function Auth() {
  const {shouldLoadContent} = useRedirectByUserCheck()
  return (
    <>
      <Head>
        <title>Others</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favicon.src} />
      </Head>


      <Layout>
        <HomePage/>
      </Layout>

      {/* <Cross size={60}/> */}
    </>
  )
}
