import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from '@/components/elements/Button'
import { AuthPage } from '@/components/templates/AuthPage/AuthPage'
import { Modal } from '@/components/layout/Modal'
import { Cross } from '@/components/elements/Cross'
import { Header } from '@/components/modules/AuthPage/Header/Header'
import { Dropdown } from '@/components/modules/AuthPage/Header/Dropdown'
import favicon from '@/public/images/favicon.png';
//import globalStyles from '../styles/globals.scss';

export default function Auth() {
  return (
    <>
      <Head>
        <title>Others</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favicon.src} />
      </Head>
      <Header/>
      <Modal childred={<AuthPage/>} />

      {/* <Cross size={60}/> */}
    </>
  )
}
