import Layout from '@/components/layout/Layout'
import { ProfilePage } from '@/components/templates/ProfilePage/ProfilePage'
import Head from 'next/head'
import favicon from '@/public/images/favicon.png';

export default function Profile(){

    return (
        <>
          <Head>
            <title>Others</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href={favicon.src} />
          </Head>
    
            {/* <Modal childred={<AuthPage/>} /> */}
    
          <Layout>
            <ProfilePage/>
          </Layout>
    
          {/* <Cross size={60}/> */}
        </>
      )
}